import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Hermano } from '../../../features/censo/censo';

@Injectable({
  providedIn: 'root',
})
export class CensoService {
  // Inject the HTTP client to make network requests
  private http = inject(HttpClient);

  // Define the base URL of your Java Spring Boot backend
  private apiUrl = 'http://localhost:8080/api/v1/hermanos';

  /**
   * Fetches the complete list of 'hermanos' from the backend API.
   * @returns An Observable emitting an array of Hermano objects.
   */
  getAllHermanos(): Observable<Hermano[]> {
    return this.http.get<Hermano[]>(this.apiUrl);
  }

  /**
   * Sends a POST request to create a new member in the database.
   * @param hermano The member data from the form (without ID, as it is generated by the database).
   * @returns An Observable with the created member.
   */
  addHermano(hermano: Omit<Hermano, 'id'>): Observable<Hermano> {
    return this.http.post<Hermano>(this.apiUrl, hermano);
  }
}
